# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: podrezo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: PulseCheck

provider:
  name: aws
  runtime: ruby3.3
  timeout: 11
  memorySize: 128
  logRetentionInDays: 14

package:
  patterns:
    - 'check.rb'

functions:
  checkPulse:
    handler: check.handler
    events:
      - schedule:
          rate: rate(10 minutes)
          input:
            targetUrl: ${env:TARGET_URL}
