# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: podrezo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: PulseCheck

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 11
  memorySize: 128
  logRetentionInDays: 14
  environment:
    # SNS Topic ARN for publishing health check results
    # This should be set via environment variable during deployment
    SNS_TOPIC_ARN: ${env:SNS_TOPIC_ARN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: ${env:SNS_TOPIC_ARN}

package:
  patterns:
    - 'test-connection.js'
    - 'sns-publisher.js'

functions:
  checkPulse:
    handler: handler.run
    environment:
      SNS_TOPIC_ARN: ${env:SNS_TOPIC_ARN}
    events:
      - schedule:
          rate: rate(10 minutes)
          input:
            targetUrl: ${env:TARGET_URL}
